#!/usr/bin/env node
/*
 * seo-head.mjs, writes a published demo's search and social metadata into its <head>.
 *
 * One code path, two callers:
 *
 *   publish-game-demo.mjs imports injectSeoHead() and runs it on every publish, so a rebuilt
 *   demo cannot reach the site without its metadata.
 *
 *   node tools/seo-head.mjs --slug <slug>   rewrites <slug>/index.html where it already sits.
 *   That exists because not every demo here arrived through publish-game-demo.mjs: /dragonhoard/
 *   is assembled by the game repo's own demo/scripts/build-demo.mjs and lands in this repo as a
 *   plain directory copy, so there is no publish step of ours to hook. Running the same function
 *   from the command line is what stops that page from needing a second, divergent copy of these
 *   rules.
 *
 * The content comes from the "seo" block of tools/demos/<slug>.json. Nothing is derived from the
 * build, because everything here is a claim about the game rather than a fact about the bundle,
 * and a claim belongs in a file a human reviews.
 *
 * Why the managed tags are REMOVED before the new ones go in, rather than simply appended:
 * a game build writes its own <title> and og: tags, and a document with two of either does not
 * average them. Browsers and crawlers both take the first one, which is the build's, which is
 * the stale one. Sweet Bomb's build shipped a title this block is specifically meant to replace,
 * so appending would have left the defect in place and reported success.
 *
 * Why canonical and og:image must be fully qualified https:// URLs, and why passing a site-root
 * path is refused outright:
 *
 *   1. publish-game-demo.mjs aborts on any root-absolute src/href in index.html, because under
 *      /<slug>/ a path like /assets/og.png resolves against the site root and 404s. Writing one
 *      here would arm that gate against the next publish.
 *   2. A share card is fetched by a machine on another host. It has no page to be relative to,
 *      so the qualified form is the only one that ever worked for og:image regardless.
 *
 * The block is delimited by HTML comments and stripped before it is rewritten, so running this
 * twice over the same file produces the same file. That matters most for the CLI, which is
 * pointed at pages that already have a block in them.
 */

import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const TOOLS_DIR = path.dirname(fileURLToPath(import.meta.url));
const SITE_DIR = path.resolve(TOOLS_DIR, '..');

export const SITE_ORIGIN = 'https://playgambitgames.com';
export const SITE_NAME = 'Gambit Games';

/* Titles are truncated by Google somewhere around 60 characters and descriptions around 160, and
   a truncated one loses whichever clause the writer put last. These are hard limits rather than
   warnings because the caller is a publish step: a run that only printed a warning would ship the
   truncated version anyway, and nobody reads a publish log that succeeded.
   The floors are not typography, they are a signal that a field was filled in as a placeholder. */
const LIMITS = {
	title: { min: 30, max: 60 },
	description: { min: 120, max: 160 },
};

const BLOCK_START = '<!-- seo:start, generated by tools/seo-head.mjs from tools/demos/<slug>.json, do not hand-edit -->';
const BLOCK_END = '<!-- seo:end -->';

/* Every tag this block owns, matched so it can be cleared out of the head first.
   [^<>]* rather than [^>]* is deliberate on two counts. It spans newlines, which it has to:
   Sweet Bomb's build formats a single <meta> across four lines. And it cannot run past the start
   of the next tag, so an attribute value that somehow contains a ">" leaves its own tag unmatched
   instead of swallowing the rest of the document. An unmatched tag then survives into the
   duplicate check at the bottom of injectSeoHead, which is a loud failure rather than a quiet
   corruption. Both quoting styles are accepted because these are hand-written game templates, not
   one bundler's output.
   Each pattern takes the whole line it sits on, its own indentation included, or removing a tag
   would leave a run of spaces behind as a whitespace-only line. */
const MANAGED_TAGS = [
	/[ \t]*<title\b[^<>]*>[\s\S]*?<\/title>[ \t]*\r?\n?/gi,
	/[ \t]*<meta\b[^<>]*\bname\s*=\s*["']description["'][^<>]*>[ \t]*\r?\n?/gi,
	/[ \t]*<meta\b[^<>]*\bproperty\s*=\s*["']og:[\w:.-]*["'][^<>]*>[ \t]*\r?\n?/gi,
	/[ \t]*<meta\b[^<>]*\bname\s*=\s*["']twitter:[\w:.-]*["'][^<>]*>[ \t]*\r?\n?/gi,
	/[ \t]*<link\b[^<>]*\brel\s*=\s*["']canonical["'][^<>]*>[ \t]*\r?\n?/gi,
];

/* Captured in three parts so the rewritten inner head can be spliced back between the original
   tags. Rebuilding it with String.replace instead would run the new head through replacement
   pattern expansion, and a game's inline CSS or JS is entitled to contain a "$&". */
const HEAD = /(<head\b[^>]*>)([\s\S]*?)(<\/head>)/i;

const escapeRe = (literal) => literal.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');

/* & first, or it would re-escape the ampersands the later replacements introduce. */
function attr(value) {
	return String(value)
		.replace(/&/g, '&amp;')
		.replace(/</g, '&lt;')
		.replace(/>/g, '&gt;')
		.replace(/"/g, '&quot;');
}

function required(seo, field, slug) {
	const value = seo[field];
	if (typeof value !== 'string' || value.trim() === '') {
		throw new Error(`tools/demos/${slug}.json: seo.${field} is missing or empty`);
	}
	return value.trim();
}

/**
 * Rewrites the <head> of a game demo's index.html with the metadata described by its manifest.
 * Throws on anything it will not silently paper over, so the caller decides whether that means
 * aborting a publish or failing a command.
 *
 * @param {string} html      the full document
 * @param {object} options
 * @param {string} options.slug  the URL segment the demo serves under, used for the canonical
 * @param {object} options.seo   the "seo" block of tools/demos/<slug>.json
 * @returns {string} the rewritten document
 */
export function injectSeoHead(html, { slug, seo }) {
	if (!seo || typeof seo !== 'object') {
		throw new Error(
			`tools/demos/${slug}.json has no "seo" block.\n` +
				`It needs title, description, image and imageAlt. A page with no <title> is the exact ` +
				`defect this step exists to prevent, so there is no sensible default to fall back to.`,
		);
	}

	const title = required(seo, 'title', slug);
	const description = required(seo, 'description', slug);
	const image = required(seo, 'image', slug);
	const imageAlt = required(seo, 'imageAlt', slug);
	const type = typeof seo.type === 'string' && seo.type.trim() !== '' ? seo.type.trim() : 'website';

	/* The em dash is banned across this project, and the one thing that reliably reintroduces it is
	   copy pasted in from somewhere else. This is the last point at which a bad character is still
	   cheap to fix, so it is checked here rather than trusted to a reviewer's eye. */
	for (const [field, value] of Object.entries({ title, description, imageAlt })) {
		if (value.includes('\u2014')) {
			throw new Error(
				`tools/demos/${slug}.json: seo.${field} contains an em dash, which this project does ` +
					`not use. Rewrite it with a comma, colon, or a full stop.`,
			);
		}
	}

	for (const [field, value] of Object.entries({ title, description })) {
		const { min, max } = LIMITS[field];
		if (value.length > max) {
			throw new Error(
				`tools/demos/${slug}.json: seo.${field} is ${value.length} characters, over the ${max} ` +
					`a search result shows. Everything past the cut is lost, so shorten it here instead.`,
			);
		}
		if (value.length < min) {
			throw new Error(
				`tools/demos/${slug}.json: seo.${field} is only ${value.length} characters, under the ` +
					`${min} this expects. That is short enough to read as a placeholder, so it stops here.`,
			);
		}
	}

	if (!image.startsWith(`${SITE_ORIGIN}/`)) {
		throw new Error(
			`tools/demos/${slug}.json: seo.image must be a fully qualified ${SITE_ORIGIN}/... URL, got ` +
				`"${image}".\nA site-root path 404s under /${slug}/ and would arm the root-absolute gate ` +
				`in publish-game-demo.mjs, and a relative one cannot be resolved at all by the crawler ` +
				`on another host that fetches the share card.`,
		);
	}

	/* Dimensions are optional, but half a pair is worse than neither: a card renderer that trusts
	   og:image:width to reserve space and never gets the height lays out against a guess. */
	const hasWidth = seo.imageWidth !== undefined && seo.imageWidth !== null;
	const hasHeight = seo.imageHeight !== undefined && seo.imageHeight !== null;
	if (hasWidth !== hasHeight) {
		throw new Error(
			`tools/demos/${slug}.json: seo.imageWidth and seo.imageHeight have to be given together ` +
				`or not at all.`,
		);
	}

	const headMatch = html.match(HEAD);
	if (!headMatch) throw new Error('index.html has no <head> to write metadata into');

	const canonical = `${SITE_ORIGIN}/${slug}/`;

	// ---------------------------------------------------------------- rebuild the head

	let head = headMatch[2];

	/* Clear the previous run's block before anything else, so a re-run replaces it rather than
	   stacking a second copy underneath. Everything between the markers is ours by definition. */
	head = head.replace(
		new RegExp(`[ \\t]*${escapeRe(BLOCK_START)}[\\s\\S]*?${escapeRe(BLOCK_END)}[ \\t]*\\r?\\n?`, 'g'),
		'',
	);

	for (const pattern of MANAGED_TAGS) head = head.replace(pattern, '');

	/* The viewport is the build's business, not this block's: a game canvas has real opinions about
	   scale and safe areas that a generic tag would flatten. It is only supplied when the build
	   shipped without one, in which case a mobile browser renders the page at 980px wide and
	   Google's mobile-friendly check fails the URL outright. */
	const hasViewport = /<meta\b[^<>]*\bname\s*=\s*["']viewport["']/i.test(head);

	/* Match the closing tag's own indentation so the block sits with the file rather than on top
	   of it. Sweet Bomb's build indents with spaces and Dragonhoard's with tabs. */
	const closeIndent = html.match(/([ \t]*)<\/head>/i)?.[1] ?? '';
	const indent = closeIndent + (closeIndent.includes('\t') ? '\t' : '  ');

	const lines = [
		BLOCK_START,
		`<title>${attr(title)}</title>`,
		`<meta name="description" content="${attr(description)}">`,
		...(hasViewport ? [] : ['<meta name="viewport" content="width=device-width, initial-scale=1">']),
		`<link rel="canonical" href="${attr(canonical)}">`,
		`<meta property="og:title" content="${attr(title)}">`,
		`<meta property="og:description" content="${attr(description)}">`,
		`<meta property="og:type" content="${attr(type)}">`,
		`<meta property="og:url" content="${attr(canonical)}">`,
		`<meta property="og:site_name" content="${attr(SITE_NAME)}">`,
		`<meta property="og:image" content="${attr(image)}">`,
		...(hasWidth
			? [
					`<meta property="og:image:width" content="${attr(seo.imageWidth)}">`,
					`<meta property="og:image:height" content="${attr(seo.imageHeight)}">`,
				]
			: []),
		`<meta property="og:image:alt" content="${attr(imageAlt)}">`,
		`<meta name="twitter:card" content="summary_large_image">`,
		`<meta name="twitter:title" content="${attr(title)}">`,
		`<meta name="twitter:description" content="${attr(description)}">`,
		`<meta name="twitter:image" content="${attr(image)}">`,
		`<meta name="twitter:image:alt" content="${attr(imageAlt)}">`,
		BLOCK_END,
	];
	const block = lines.map((line) => `${indent}${line}`).join('\n');

	head = `${head.replace(/\s*$/, '\n')}${block}\n${closeIndent}`;

	let out =
		html.slice(0, headMatch.index) +
		headMatch[1] +
		head +
		headMatch[3] +
		html.slice(headMatch.index + headMatch[0].length);

	// ---------------------------------------------------------------- guard rails

	/* A stripping regex that failed to match its target would leave the build's own tag in place,
	   and the first one wins, which means the page would keep the stale title while this reported
	   success. Counting them afterwards is what turns that into a visible failure. */
	const finalHead = out.match(HEAD)?.[2] ?? '';
	const duplicates = [
		['<title>', (finalHead.match(/<title\b/gi) ?? []).length],
		['meta name="description"', (finalHead.match(/\bname\s*=\s*["']description["']/gi) ?? []).length],
		['link rel="canonical"', (finalHead.match(/\brel\s*=\s*["']canonical["']/gi) ?? []).length],
		['meta property="og:title"', (finalHead.match(/\bproperty\s*=\s*["']og:title["']/gi) ?? []).length],
	];
	const stacked = duplicates.filter(([, count]) => count !== 1);
	if (stacked.length > 0) {
		throw new Error(
			`the rewritten head does not hold exactly one of each managed tag:\n  ` +
				stacked.map(([name, count]) => `${name}: ${count}`).join('\n  ') +
				`\nThe build's own copy was probably formatted in a way the strip patterns in ` +
				`tools/seo-head.mjs do not recognise. Nothing was written.`,
		);
	}

	/* An <html> with no lang is the single most commonly flagged accessibility defect there is,
	   and a screen reader with no language picks a voice by guessing. The games are English. */
	out = out.replace(/<html\b([^>]*)>/i, (tag, attrs) =>
		/\blang\s*=/i.test(attrs) ? tag : `<html${attrs} lang="en">`,
	);

	return out;
}

// ---------------------------------------------------------------------- command line

/* Only when run directly. Imported by publish-game-demo.mjs, this half does nothing. */
if (import.meta.url === pathToFileURL(process.argv[1] ?? '').href) {
	const index = process.argv.indexOf('--slug');
	const slug = index === -1 || index === process.argv.length - 1 ? null : process.argv[index + 1];

	const die = (message) => {
		console.error(`seo-head: ${message}`);
		process.exit(1);
	};

	if (!slug) die('missing --slug (the published directory to rewrite, e.g. --slug dragonhoard)');
	if (!/^[a-z0-9]+(-[a-z0-9]+)*$/.test(slug)) die(`--slug must be lowercase kebab-case, got "${slug}"`);

	const manifestPath = path.join(TOOLS_DIR, 'demos', `${slug}.json`);
	if (!existsSync(manifestPath)) die(`no manifest at ${path.relative(SITE_DIR, manifestPath)}`);

	const indexPath = path.join(SITE_DIR, slug, 'index.html');
	if (!existsSync(indexPath)) die(`nothing published at ${slug}/index.html`);

	const manifest = JSON.parse(readFileSync(manifestPath, 'utf8'));
	const before = readFileSync(indexPath, 'utf8');

	let after;
	try {
		after = injectSeoHead(before, { slug, seo: manifest.seo });
	} catch (error) {
		die(error.message);
	}

	if (after === before) {
		console.log(`${slug}/index.html already carries this metadata, nothing to write`);
	} else {
		writeFileSync(indexPath, after);
		console.log(`rewrote the <head> of ${slug}/index.html`);
		console.log(`      title  ${manifest.seo.title}`);
		console.log(`  canonical  ${SITE_ORIGIN}/${slug}/`);
	}
}
